# Generated by Django 4.1.4 on 2023-08-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('no_of_employees', models.IntegerField()),
            ],
        ),
    ]
