# Generated by Django 4.1.4 on 2023-08-14 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('Permanent', 'PERMANENT'), ('Temporary', 'TEMPORARY')], default='Permanent', max_length=100)),
                ('description', models.TextField()),
                ('experience_required', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vacant', models.PositiveIntegerField()),
                ('gender_required', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=8)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'unique_together': {('title', 'is_published', 'branch', 'department')},
            },
        ),
        migrations.CreateModel(
            name='EducationalRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('None required', 'None'), ('Grade 8', 'G8'), ('Grade 10', 'G10'), ('Grade 12', 'G12'), ('Diploma', 'Diploma'), ('BSc', 'BSC'), ('MSc', 'MSC'), ('MSc/BSc', 'MSC/BSC')], default='None required', max_length=255)),
                ('qualification_department', models.TextField(blank=True, null=True)),
                ('minimum_grade_required', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_requirement', to='jobs.job')),
            ],
        ),
    ]
